bot.username = MonopolyBot
bot.token = 1395168119:AAFHiYl8PV2ZWYvUPW6xodXSPJO5g6xmCnk

spring.datasource.url=jdbc:postgresql://localhost:5432/monopoly_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.mvc.hiddenmethod.filter.enabled=true

logging.level.org.springframework.web=DEBUG
